# Generated by Django 3.0.4 on 2020-03-24 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('summary', models.TextField()),
                ('image', models.FilePathField(path='/img')),
                ('banner_image', models.FilePathField(path='/static/images/blog')),
                ('reference_url', models.URLField(default='https://github.com/tauovir')),
                ('is_publish', models.IntegerField(choices=[(1, 'Not Publish'), (2, 'Publish')])),
                ('publish_date', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('summary', models.TextField()),
                ('code', models.TextField()),
                ('image', models.FilePathField(path='/static/images/blog')),
                ('is_publish', models.IntegerField(choices=[(1, 'Not Publish'), (2, 'Publish')])),
                ('publish_date', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Posts')),
            ],
        ),
    ]
