# Generated by Django 3.0.4 on 2020-03-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.FilePathField(path='/static/images/blog'),
        ),
    ]
