# Generated by Django 3.0.4 on 2020-04-25 18:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='short_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='technologies',
            name='rate',
            field=models.SmallIntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='User_Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Profile')),
            ],
        ),
    ]
