# Generated by Django 3.0.4 on 2020-04-25 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200426_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_interest',
            old_name='Profile',
            new_name='profile',
        ),
    ]
