# Generated by Django 3.0.4 on 2020-03-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200325_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdetail',
            name='image',
            field=models.FilePathField(path='C:/web_app/blog/static/assets/images/blog'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='banner_image',
            field=models.FilePathField(path='C:/web_app/blog/static/assets/images/blog'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.FilePathField(path='C:/web_app/blog/static/assets/images/blog'),
        ),
    ]
