# Generated by Django 3.0.4 on 2020-03-24 22:54

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200325_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdetail',
            name='image',
            field=models.FilePathField(path=blog.models.imagePath),
        ),
        migrations.AlterField(
            model_name='postdetail',
            name='is_publish',
            field=models.IntegerField(choices=[(0, 'Not Publish'), (1, 'Publish')]),
        ),
        migrations.AlterField(
            model_name='postdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='banner_image',
            field=models.FilePathField(path=blog.models.imagePath),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.FileField(upload_to=blog.models.imagePath),
        ),
        migrations.AlterField(
            model_name='posts',
            name='is_publish',
            field=models.IntegerField(choices=[(0, 'Not Publish'), (1, 'Publish')]),
        ),
        migrations.AlterField(
            model_name='posts',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
