# Generated by Django 3.0.4 on 2020-03-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200325_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdetail',
            name='image',
            field=models.ImageField(upload_to='blog.static/assets/images/blog/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='banner_image',
            field=models.ImageField(upload_to='blog.static/assets/images/blog/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(upload_to='blog.static/assets/images/blog/'),
        ),
    ]
