# Generated by Django 3.0.4 on 2020-05-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200430_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
