# Generated by Django 3.0.4 on 2020-03-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200325_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdetail',
            name='image',
            field=models.ImageField(upload_to='blog/static/assets/images/blog/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='banner_image',
            field=models.ImageField(upload_to='blog/static/assets/images/blog/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(upload_to='blog/static/assets/images/blog/'),
        ),
    ]
