# Generated by Django 3.0.4 on 2020-03-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200325_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('skils', models.TextField()),
                ('blog_summary', models.TextField()),
                ('image', models.ImageField(upload_to='blog/static/assets/images/blog/')),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
