# Generated by Django 3.0.4 on 2020-04-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='summary',
            new_name='brief_summary',
        ),
        migrations.AddField(
            model_name='about',
            name='blog_image',
            field=models.ImageField(default='bank', upload_to='blog/static/assets/images/blog/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='detail_summary',
            field=models.TextField(default='detail'),
            preserve_default=False,
        ),
    ]
