# Generated by Django 3.0.4 on 2020-04-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200403_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='banner_image',
            field=models.ImageField(blank=True, upload_to='banner_image'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(upload_to='blog_image'),
        ),
    ]
