# Generated by Django 3.0.4 on 2020-04-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200411_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='blog_image',
            field=models.ImageField(upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='postdetail',
            name='image',
            field=models.ImageField(upload_to='blog_image'),
        ),
    ]
