# Generated by Django 3.0.4 on 2020-04-10 21:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200411_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='summary',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
